- name: nodejs準備
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

- name: nodejsインストール
  become_user: root
  become: yes
  yum:
    name: nodejs
    state: latest

- name: yarnインストール準備
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  become: yes
  become_user: root

- name: yarnインストール
  yum:
    name: yarn
    state: latest
  become: yes
  become_user: root